apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkding-http
  namespace: linkding
spec:
  entryPoints:
    - websecure
    - web
  routes:
  - match: Host(`linkding-local.dankai.dev`)
    kind: Rule
    services:
      - name: linkding
        port: 9090
    
