apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: synology-csi
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi-talos
      version: "0.9.4"
      sourceRef:
        kind: HelmRepository
        name: synology-csi
        namespace: flux-system
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
