apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageclass: synology-csi-delete
  resources:
    requests:
      storage: 1Gi
