apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-prod-values
      valuesKey: values.yaml
