apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: /homelab/prod-grafana-admin
      property: admin-password
  - secretKey: admin-user
    remoteRef:
      key: /homelab/prod-grafana-admin
      property: admin-user
