apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./monitoring/controllers/production
  retryInterval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
  prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: monitoring-configs
#   namespace: flux-system
# spec:
#   #decryption:
#   #  provider: sops
#   #  secretRef:
#   #    name: sops-age
#   interval: 1m0s
#   path: ./monitoring/configs/production
#   retryInterval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   timeout: 5m
#   prune: true
