apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-credentials
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: mealie-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /homelab/prod-mealie-credentials
      property: POSTGRES_PASSWORD
  - secretKey: username
    remoteRef:
      key: /homelab/prod-mealie-credentials
      property: POSTGRES_USER
