apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:  
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      volumes:
        - name: audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-data-pvc
        - name: podcasts
          persistentVolumeClaim:
            claimName: podcasts-data-pvc
        - name: metadata
          persistentVolumeClaim:
            claimName: metadata-data-pvc
        - name: config
          persistentVolumeClaim:
            claimName: config-data-pvc
      containers:
      - image: ghcr.io/advplyr/audiobookshelf:2.29.0
        ports:
          - containerPort: 3005
        name: audiobookshelf
        envFrom:
          - configMapRef:
              name: config
        volumeMounts:
          - name: audiobooks
            mountPath: /audiobooks
          - name: podcasts
            mountPath: /podcasts
          - name: metadata
            mountPath: /metadata
          - name: config
            mountPath: /config
