apiVersion: v1
kind: Service
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
  namespace: audiobookshelf
spec:
  ports:
  - name: audiobookshelf
    port: 3005
    protocol: TCP
    targetPort: 3005
  selector:
    app: audiobookshelf
  type: ClusterIP
