apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: prod-linkding-cnpg
  namespace: database
spec:
  instances: 3
  storage:
    size: 1Gi
    storageClass: synology-iscsi-retain
  bootstrap:
    initdb:
      database: linkding
      owner: linkding
      secret:
        name: linkding-credentials
