apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: linkding-credentials
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /homelab/prod-linkding-credentials
      property: password
  - secretKey: username
    remoteRef:
      key: /homelab/prod-linkding-credentials
      property: username
