apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkding-credentials
  namespace: linkding
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: linkding-credentials
    creationPolicy: Owner
  data:
  - secretKey: LD_SUPERUSER_PASSWORD
    remoteRef:
      key: /homelab/prod-linkding-credentials
      property: LD_SUPERUSER_PASSWORD
  - secretKey: LD_SUPERUSER_NAME
    remoteRef:
      key: /homelab/prod-linkding-credentials
      property: LD_SUPERUSER_NAME
