apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
  name: synostorage
provisioner: csi.san.synology.com
parameters:
  fsType: 'ext4'
  dsm: '192.168.1.222'
  location: '/volume2'
  formatOptions: '--nodiscard'
reclaimPolicy: Retain
allowVolumeExpansion: true