apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homelab-cluster
  namespace: database
spec:
  instances: 3
  storage:
    size: 100Gi
    storageClass: synology-iscsi-retain
  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: homelab-cluster-app
