apiVersion: batch/v1
kind: Job
metadata:
  name: db-init
  namespace: database
spec:
  template:
    spec:
      initContainers:
      - image: postgres:alpine3.21
        name: db-init
        command:
        - sh
        - -c
        - |
          until pg_isready -h homelab-cluster-rw.database.svc.cluster.local -p 5432; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 5
          done
          echo "Database is ready!"
      containers:
      - image: postgres:alpine3.21
        name: db-create
        command: ["/bin/sh", "-c"]
        args:
        - |
          psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@homelab-cluster-rw.database.svc.cluster.local:5432/postgres" <<EOF
          CREATE DATABASE linkding;
          CREATE USER $LINKDING_PSQL_USER WITH PASSWORD '$LINKDING_PSQL_PASSWORD';
          GRANT ALL PRIVILEGES ON DATABASE linkding TO $LINKDING_PSQL_USER;
          EOF

          psql "postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@homelab-cluster-rw.database.svc.cluster.local:5432/linkding" <<EOF
          GRANT ALL ON SCHEMA public TO $LINKDING_PSQL_USER;
          EOF
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: homelab-cluster-app
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: homelab-cluster-app
              key: password
        - name: LINKDING_PSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-postgres
              key: password
        - name: LINKDING_PSQL_USER
          valueFrom:
            secretKeyRef:
              name: linkding-db-secret
              key: username
      restartPolicy: OnFailure
