apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ghcr-access-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .dockerconfigjson | toString }}"
    name: ghcr-access-secret
    creationPolicy: Owner
  data:
  - secretKey: .dockerconfigjson
    remoteRef:
      key: /homelab/prod-ghcr-access-secret
