apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: synology-csi-secret
  namespace: synology-csi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: synology-csi-secret
    creationPolicy: Owner
  data:
  - secretKey: client-info.yaml
    remoteRef:
      key: /homelab/prod-synology-csi-secret
