apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
      storageclass: synology-csi-delete
