apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkding-data-pvc
spec:
  storageClassName: synology-csi-retain
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
