apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-admin
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: parameterstore
    kind: ClusterSecretStore
  target:
    name: homelab-cluster-app
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: /homelab/prod-homelab-cluster-app
      property: password
  - secretKey: username
    remoteRef:
      key: /homelab/prod-homelab-cluster-app
      property: username
